name: Generate
on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - run: yarn install
      - run: yarn generate
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: bjerk-bot
          commit_user_email: bjerkbot@bjerk.io
          commit_message: "chore: add protoc generated code"